### PR TITLE
update recording-requests example code

### PR DESCRIPTION
**Pull request by chadkirby**

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Hey @chadkirby ! Thanks for the PR!!! Looks like we've got to unbreak our CI system going awry in `master`, then we'll turn back to this!

**Comment by boygirl** [comment]
Looks like the CI failure was introduced here: https://github.com/FormidableLabs/yesno/pull/51
Tests are failing on node 10 but not 8

**Comment by stevenmusumeche** [comment]
The tests pass on 10.13 and 10.14, but fail on 10.15.  I'm tracking it down.

**Comment by stevenmusumeche** [comment]
There's a fix for failing CI in #57

**Comment by stevenmusumeche** [comment]
@ryan-roemer tests are passing, if you'd like to review the PR now

**Pull request merged**
